### ISSUE TITLE
"undefined" from DOM.Event.KeyboardEvent.code in IE11

### ISSUE THREAD

**Issue by grumpi** [purescript-contrib/purescript-dom#101]
In IE11 11.0.9600.18666, with `purescript-dom` version `4.3.1`, I see `undefined` as result of `code event`.

Chrome and Firefox seem to work fine. `key event` works just fine in all three browsers I tested.

Reading through https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code, it looks like `event.code` is not implemented in IE11.

What is the policy on dealing with browser compatibility? I suppose one could either try to polyfill these, or warn on pursuit that this is actually something that isn't supported by many browsers.

ETA: reading through a few more pages (in particular, the README of this repository), I realize that polyfilling things is out of scope for `purescript-dom`. Coming from Elm, the misunderstanding on my side was that this is the package to use for dealing with "all things DOM-related". Apparently, I need to use another package to get access to `keyCode` (which according to caniuse.com is the only thing that is widely enough supported for my use case). :)

I'm leaving this here as an anecdotal first-use experience.

**Comment by garyb** [comment]
Sorry you didn't get an answer on this earlier, I was on holiday last week. Including a polyfill is what I would have recommended though, as you noted in the new docs. :)

**Comment by grumpi** [comment]
No worries, I got the answer from your colleagues on the functional programming slack. That's why I figured the best way to give back is to help out a tiny bit with adding that hint to the docs. :)
