### ISSUE TITLE
eventListener missing eff?

### ISSUE THREAD

**Issue by nwolverson** [purescript-contrib/purescript-dom#12]
This type seems suspicious to me:

    eventListener :: forall eff a. (Event -> Eff (dom :: DOM) a) -> EventListener eff

is that missing an `| eff`? If the handler itself isn't allowed to do `eff` I don't see that you'd have put it in the type.

**Comment by garyb** [comment]
Yep, it should have the `eff`. I think in fact it should be: 

``` purescript
eventListener :: forall eff a. (Event -> Eff (dom :: DOM | eff) a) -> EventListener (dom :: DOM | eff)
```

**Comment by garyb** [comment]
(To prevent errors with duplicate rows)
