### ISSUE TITLE
How to get attributes from a Node type

### ISSUE THREAD

**Issue by naglalakk** [purescript-contrib/purescript-dom#149]
I'm wondering how I would get a data-attribute from a Node. From the documentation I see I can get attributes of an Element but not a Node. I can convert an Element to a Node but not vice versa? 
I'm crossing a bit into purescript-halogen in my code example but so this is my code

Query
```
data Query a 
  = LoadMailingLists a 
  | SendMessage a
  | SetSelected MouseEvent a
```

HTML DSL
```
    HH.li
      [ HP.attr (HH.AttrName "data-id") (show opt.id) 
      , HE.onClick (HE.input SetSelected)]
      [ HH.text opt.name ]
```

Handler
```
    SetSelected me next -> do
      let node = currentTarget $ mouseEventToEvent me
      pure next
```

What I want to get is the data-id attribute I set above in the HTML DSL. I get the node by converting the mouseEvent to an Event and from there I can get the currentTarget. But I'm not sure where to go from here. What would be the best way to do this?

**Comment by garyb** [comment]
Upcasting is a bit of a pain, essentially you just `toForeign` whatever it is you have and then `read` it back as the type that you want.

`purescript-dom-classy` has some classes that help, as at least the `toForeign` step can be avoided, and it uses `Maybe` rather than "`F`" (`ExceptT` of foreign errors).

**Comment by naglalakk** [comment]
Ahh ok understood. I will take a look at purescript-dom-classy. Thank you very much for your reply and this library. Closing this issue/question :)
