### ISSUE TITLE
Type of getElementById?

### ISSUE THREAD

**Issue by sharkdp** [purescript-contrib/purescript-dom#16]
Currently, `getElementById` is defined in the module `DOM.Node.NonDocumentTypeChildNode` with the following type:
``` purescript
getElementById :: forall eff. ElementId -> NonDocumentTypeChildNode -> Eff (dom :: DOM | eff) (Nullable Element)
```
Maybe I am misunderstanding something, but I don't think `getElementById` works on a single node level.. so I would rather expect this to be in `DOM.Node.Document` and to work on `Document` instead of `NonDocumentTypeChildNode`:
``` purescript
getElementById :: forall eff. ElementId -> Document -> Eff (dom :: DOM | eff) (Nullable Element)
```

See also: https://developer.mozilla.org/en-US/docs/Web/API/Document/getElementById

**Comment by garyb** [comment]
According to the DOM4 spec, this is correct: http://www.w3.org/TR/dom/#nonelementparentnode

Every `Document` is a `NonDocumentTypeChildNode`, and there is a coercion for it [provided here](https://github.com/purescript-contrib/purescript-dom/blob/e8a73fce5f6b525a16cc8790f7b09ae08fd08530/src/DOM/Node/Types.purs#L19-L20)

**Comment by garyb** [comment]
Oh, sorry, I see the problem now... yes, looks like I made the same mistake implementing it as I did just describing it :)

The interfaces for `NonDocumentTypeChildNode` and `NonElementParentNode` have swapped implementations currently... thanks!

**Comment by sharkdp** [comment]
Well, I was also wrong, but that is the solution, yes. Thanks!
