### ISSUE TITLE
compilation issues

### ISSUE THREAD

**Issue by fisx** [purescript-contrib/purescript-dom#22]
I know haskell, but i'm very new to purescript.  I hope this is a legitimate issue for somebody else but me?

In my first toy project, I get the following error (psc 0.7.4.0):

```
Error at .../bower_components/purescript-dom/src/DOM/Node/ChildNode.purs line 8, column 1 - line 11, column 1:
  Conflicting imports for Document from modules DOM and DOM.Node.Types
See https://github.com/purescript/purescript/wiki/Error-Code-ConflictingImports for more information, or to contribute content related to this error.
```

This does not happen when I install purescript-dom, but only when I build my own package that depends on it.

Any wild guesses?  I'll keep looking and will update this issue if I find anything.

**Comment by fisx** [comment]
Ok, I think I'm stuck.  This is what I understand.

Appearently psc thinks that `Document` is a symbol imported both from modules `DOM` and `DOM.Node.Types`, but `DOM` only exports the `DOM` effect type, so that far the error message is at least confusing.

When I went to `DOM.Node.Event` (where the error occurs first, in contrast to the error message I posted above) and change the second conflicting import to this:

```haskell
import DOM.Node.Types hiding (Document)
```

I get the error that `Document` is not exported from this module, which is wrong.

Looks like I need help with this...

thanks for listening in so far!

**Comment by fisx** [comment]
I forgot to mention: `purescrpit-dom#0.2.0`.

**Comment by garyb** [comment]
Have you tried clearing your `ouput` folder? I suspect you had an older version of `purescript-dom` originally and compiled that, as previously `Document` did live in `DOM`.

**Comment by fisx** [comment]
yes, that seems to be what made me stumble.  thanks!

(if there is a place where the compiler mechanics are explained to this level of detail, could you post the link here?  if not, and in the unlikely event that i can find the time to write something up: should it go to the book?)
