### ISSUE TITLE
Allow to get / set node.value

### ISSUE THREAD

**Issue by pierrebeaucamp** [purescript-contrib/purescript-dom#37]
Hi,

I'm trying to achieve the equivalent of [`node.value`](http://stackoverflow.com/a/4173414) (not `node.nodeValue`), but I can't find a function for it in the library. In contrast, `purescript-simple-dom` comes with [unsafeValue](https://github.com/aktowns/purescript-simple-dom/blob/master/src/Data/DOM/Simple/Unsafe/Element.js#L145), which does the job just fine.

Am I missing something obvious here? If not, I would be glad to submit a PR, but I wanted to ask first.

**Comment by garyb** [comment]
No, you're not, this is not at all comprehensive yet, because trying to implement the entire DOM4 and HTML5 specs at once drove me crazy, so now I add features as needed/requested :wink:

The problem here is, we need to implement the `HTMLInputElement` interface (or something like that - the type that does actually have `value` defined according to its IDL), as this library is supposed to be implementing standards.

At a minimum that means introducing the foreign type, a coercion to `HTMLElement`, and a `Foreign` instance in `DOM.HTML.Types`, and then the `getValue` / `setValue` functions in a new `DOM.HTML.HTMLInputElement` module.

**Comment by pierrebeaucamp** [comment]
Ah, I see.

However, the `value` attribute is also present in the `<button>`, `<option>`, `<li>`, `<meter>`, `<progress>` and `<param>` elements ([source](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes)).

So, instead of creating new foreign types for each of those elements, maybe it's easier to create a `hasAttribute` function, which will check a provided `HTMLElement`. 

But, to be honest, I never looked at the DOM this detailed, so there might be more to it.

**Comment by garyb** [comment]
This library is supposed to be implementing the specs, so although that's a possible approach I'd rather do it "properly".

Ideally `simple-dom` would be implemented on top of this library so the types could be shared amongst any DOM-related code, and `simple-dom` would just be providing a more convenient interface to this somewhat unfriendly but unopinionated set of bindings.

I've started working on adding the various `HTMLElement` variations now, but not quite there yet: https://github.com/purescript-contrib/purescript-dom/tree/html-elements

**Comment by pierrebeaucamp** [comment]
Alright, thank you for starting that branch. I'll see if I can find some free time to contribute to it.
Do you prefer this issue to stay open or should I close it?

**Comment by garyb** [comment]
Keep it open for now, I'll close it when the PR that adds all the new stuff is merged. :)

I've added all the modules to the branch that need implementing now, with IDL fragments for their interfaces according to the spec. There might be a few new types that need adding too, like, `DOMTokenList` but I think it's mostly stubbed out now.

If you don't have time to work on it though, no worries. I'll just keep chipping away at it a bit every day, it's something that probably should have been done a while ago anyway!

**Comment by garyb** [comment]
Sorry about the time it took to finish this up, but I think it should now be possible with #41 merged.

**Comment by pierrebeaucamp** [comment]
Wow, that was a lot of work. Thank you, I'll give it a try.
