### ISSUE TITLE
navigator.geolocation

### ISSUE THREAD

**Issue by pierrebeaucamp** [purescript-contrib/purescript-dom#43]
Hi,

I created bindings for the [Geolocation API](https://www.w3.org/TR/geolocation-API/) at [pierrebeaucamp/purescript-geolocation](https://github.com/pierrebeaucamp/purescript-geolocation). I haven't published it on NPM yet, as I don't know if it really needs its own package.

I would appreciate some feedback if I should open a PR to merge my repo into purescript-dom or if it's better to publish purescript-geolocation on its own.

Thanks

**Comment by garyb** [comment]
I think publishing `purescript-geolocation` as its own thing makes sense, or perhaps name it `purescript-dom-geolocation` to be clear it's talking about the browser API for such.

Probably the XHR stuff shouldn't be in `purescript-dom` either, and should be `purescript-dom-xhr` or something like that (I think @zudov suggested something similar elsewhere). Although all these things are browsery, I wasn't intending on providing one monolthic library for all the APIs, this was supposed to be focused around the "core DOM" stuff really.

**Comment by pierrebeaucamp** [comment]
Thank you for the feedback. Renaming it `purescript-dom-geolocation` is a good idea.

**Comment by texastoland** [comment]
Most of `navigator` is missing. It'd be nice to have all the standard APIs here but I can also see the case for modularity.

**Comment by garyb** [comment]
PRs welcome :stuck_out_tongue: 

I wasn't suggesting that every part of the DOM APIs should be split out necessarily, just those that aren't part of the core DOM/HTML APIs. `navigator.userAgent` is part of the `HTML5` API, so is welcome to reside here.

**Comment by texastoland** [comment]
Ha you commented right after I deleted. I was looking for `userAgent` but according to MDN it's deprecated. I still need it but may not be appropriate here.
