### ISSUE TITLE
Halogen combatibility issues

### ISSUE THREAD

**Issue by deamme** [purescript-contrib/purescript-dom#52]
Before Halogen can be updated for Purescript v0.9.1 it needs these modules exposed:
- DOM.Event.DragEvent.DataTransfer
- DOM.Event.EventTypes

Errors:
https://gist.github.com/deamme/2749d127f38afe00ca00e740d8879d8d

**Comment by garyb** [comment]
These do still exist, but the modules have moved:

- `DOM.Event.DragEvent.DataTransfer` -> `DOM.HTML.Event.DragEvent.DataTransfer`
- `DOM.Event.EventTypes` -> `DOM.HTML.Event.EventTypes`
