### ISSUE TITLE
HTMLTableSectionElement insertRow argument order swapped

### ISSUE THREAD

**Issue by ajscholl** [purescript-contrib/purescript-dom#56]
`foreign import insertRow' :: forall eff. Int -> HTMLTableSectionElement -> Eff (dom :: DOM | eff) HTMLElement`

The Int is passed first...

```
exports["insertRow'"] = function (section) {
  return function (index) {
    return function () {
      return section.insertRow(index);
    };
  };
};
```

The Int is expected at the second position... calling `insertRow'` or `insertRow` thus always fails.

The same also applies to the code for HTMLTableElement

**Comment by garyb** [comment]
Thanks for the report!
