### ISSUE TITLE
Missing HTMLAudioElement definitions and types

### ISSUE THREAD

**Issue by justinwoo** [purescript-contrib/purescript-dom#77]
Right now I have a project where I could use purescript-dom-classy to convert my HTMLElement types to the proper ones, but I'm using currentTime and setCurrentTime from HTMLMediaElement on an audio element. This causes my unsafeCoerced code to work but of course, fails when using fromHTMLElement since it tries to parse to the media element and fails.

Should we add the audio element types and code to work with them?

**Comment by garyb** [comment]
Yes please, it's not missing intentionally!

**Comment by justinwoo** [comment]
Ah, sorry, I think I've just misunderstood. I should be using `htmlAudioElementToHTMLMediaElement` instead? Looks like the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/HTMLAudioElement) are saying that this just inherits from HTMLMediaElement anyhow.

**Comment by garyb** [comment]
Ah right, yeah that looks like the case for this element then, since it has an empty interface :)
