### ISSUE TITLE
add requestAnimationFrame and friends

### ISSUE THREAD

**Issue by coot** [purescript-contrib/purescript-dom#90]
[requestAnimationFrame](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame)
[requestIdleCallback](https://developer.mozilla.org/en-US/docs/Web/API/Window/requestIdleCallback)

**Comment by coot** [comment]
But maybe the right place is the [purescript-js-timers](https://github.com/purescript-contrib/purescript-js-timers) repo.

**Comment by garyb** [comment]
I think adding them here is probably right - node doesn't have rAF, and a dom dependency `-dom` suggests browser-y use cases, so it seems appropriate.

**Comment by garyb** [comment]
Resolved by #91
